Repository cesarsnina/placement-backend, pull requests merged in 2022-06, with the labels that each got.

#37 Danny
  api/v1/controllers/jobsController.js
  api/v1/models/Job.js
Labels: backend, fixed

#38 fix: syntax error
  api/v1/controllers/jobsController.js
Labels: backend, fixed

#40 fix: include skills with jobs json data
  api/v1/controllers/jobsController.js
Labels: backend

#41 Support skills endpoint
  api/v1/controllers/skillsController.js
  api/v1/routes/skill.js
  server/app.js
Labels: enhancement, backend

#42 Update delete user
  api/v1/controllers/jobsController.js
  api/v1/controllers/usersController.js
  api/v1/models/Job.js
  api/v1/models/index.js
  api/v1/routes/job.js
  api/v1/routes/user.js
Labels: backend

#43 feat: get job by id
  api/v1/controllers/jobsController.js
Labels: backend

#44 Get job by id action and endpoint
  api/v1/controllers/jobsController.js
  api/v1/routes/job.js
  api/v1/routes/user.js
Labels: backend

#45 fix: undefined id value
  api/v1/controllers/jobsController.js
  api/v1/controllers/usersController.js
Labels: backend, fixed

#51 feat: send json
  api/v1/controllers/jobsController.js
Labels: backend

#52 fix: syntax error
  api/v1/controllers/jobsController.js
Labels: backend, fixed

#53 debug create job by user id
  api/v1/controllers/jobsController.js
Labels: bug, backend
